### ISSUE TITLE
Is this used for d.ts file generation?

### ISSUE THREAD

**Issue by kmuthukumar23** [microsoft/api-extractor.com-website#18]
Hi ,

I have some doubts regarding JsDoc comment parsing while generating the d.ts file. I want restrict some internal @tag parameters when generating the .d.ts file. 

is this possible? Can any one help regard this. 

Also report this related in typeDoc
https://github.com/TypeStrong/typedoc/issues/1099

**Comment by octogonz** [comment]
@kmuthukumar23 this repo is for the https://api-extractor.com/ website.

It sounds like you're proposing an enhancement for the API Extractor tool itself.  Could you open an issue in the [web-build-tools](https://github.com/microsoft/web-build-tools/issues) repo instead?

API Extractor uses [TSDoc](https://github.com/microsoft/tsdoc) comments instead of JSDoc.  The syntax is very similar, though.

API Extractor produces a .d.ts rollup file as its output.  It sounds like you're asking for the doc comments to get normalized in the generated .d.ts file, by deleting certain internal tags.  This seems useful, and within the scope of what API Extractor does.  For example, we've been wanting to trim the [@privateRemarks](https://api-extractor.com/pages/tsdoc/tag_privateremarks/) tags from the output .d.ts files.

However, there are some design questions for your proposal.  It would be helpful for you to share some realistic examples of doc comment inputs and the expected outputs.  Please do this in the new issue.
